#pragma once

// Parameter indices (order in the Effect Controls panel) and stable disk IDs.
// Never renumber disk IDs once projects have been saved with the plug-in.

enum {
    P_INPUT = 0,

    P_LENS_TOPIC,
    P_LENS_PRESET,
    P_FOCAL_LENGTH,
    P_FSTOP,
    P_SENSOR,
    P_SENSOR_WIDTH,
    P_LENS_TOPIC_END,

    P_FOCUS_TOPIC,
    P_DEFOCUS_MODE,
    P_DEFOCUS_AMOUNT,
    P_DEPTH_LAYER,
    P_DEPTH_WHITE,
    P_DEPTH_ENCODING,
    P_DEPTH_NEAR,
    P_DEPTH_FAR,
    P_FOCUS_DISTANCE,
    P_FOCUS_PICK,
    P_FOCUS_POINT,
    P_DEFOCUS_SCALE,
    P_FOCUS_TOPIC_END,

    P_APERTURE_TOPIC,
    P_BLADES,
    P_BLADE_CURVATURE,
    P_BLADE_ROTATION,
    P_OBSTRUCTION,
    P_CUSTOM_APERTURE,
    P_APERTURE_TOPIC_END,

    P_CHAR_TOPIC,
    P_CATEYE,
    P_CHROMATIC,
    P_SPHERICAL,
    P_COMA,
    P_ASTIGMATISM,
    P_SQUEEZE,
    P_ONION,
    P_ONION_FREQ,
    P_TEXTURE,
    P_TEXTURE_SCALE,
    P_TEXTURE_SEED,
    P_CHAR_TOPIC_END,

    P_HIGHLIGHT_TOPIC,
    P_HI_THRESHOLD,
    P_HI_GAIN,
    P_HIGHLIGHT_TOPIC_END,

    P_RENDER_TOPIC,
    P_QUALITY,
    P_MAX_BLUR,
    P_LAYERS,
    P_COLOR_MODE,
    P_OPTICAL_CENTER,
    P_VIEW,
    P_RENDER_TOPIC_END,

    P_COUNT
};

enum {
    ID_LENS_TOPIC = 1,
    ID_LENS_PRESET,
    ID_FOCAL_LENGTH,
    ID_FSTOP,
    ID_SENSOR,
    ID_SENSOR_WIDTH,
    ID_LENS_TOPIC_END,
    ID_FOCUS_TOPIC,
    ID_DEFOCUS_MODE,
    ID_DEFOCUS_AMOUNT,
    ID_DEPTH_LAYER,
    ID_DEPTH_WHITE,
    ID_DEPTH_ENCODING,
    ID_DEPTH_NEAR,
    ID_DEPTH_FAR,
    ID_FOCUS_DISTANCE,
    ID_FOCUS_PICK,
    ID_FOCUS_POINT,
    ID_DEFOCUS_SCALE,
    ID_FOCUS_TOPIC_END,
    ID_APERTURE_TOPIC,
    ID_BLADES,
    ID_BLADE_CURVATURE,
    ID_BLADE_ROTATION,
    ID_OBSTRUCTION,
    ID_CUSTOM_APERTURE,
    ID_APERTURE_TOPIC_END,
    ID_CHAR_TOPIC,
    ID_CATEYE,
    ID_CHROMATIC,
    ID_SPHERICAL,
    ID_COMA,
    ID_ASTIGMATISM,
    ID_SQUEEZE,
    ID_ONION,
    ID_ONION_FREQ,
    ID_TEXTURE,
    ID_TEXTURE_SCALE,
    ID_TEXTURE_SEED,
    ID_CHAR_TOPIC_END,
    ID_HIGHLIGHT_TOPIC,
    ID_HI_THRESHOLD,
    ID_HI_GAIN,
    ID_HIGHLIGHT_TOPIC_END,
    ID_RENDER_TOPIC,
    ID_QUALITY,
    ID_MAX_BLUR,
    ID_LAYERS,
    ID_COLOR_MODE,
    ID_OPTICAL_CENTER,
    ID_VIEW,
    ID_RENDER_TOPIC_END
};

// Checkout IDs used between PreRender and SmartRender.
enum { CHECKOUT_INPUT = 1, CHECKOUT_DEPTH = 2, CHECKOUT_APERTURE = 3 };

#define LENSYUM_NAME        "Lensyum"
#define LENSYUM_MATCH_NAME  "RAMIR Lensyum"
#define LENSYUM_CATEGORY    "Lensyum"

#define LENSYUM_MAJOR   1
#define LENSYUM_MINOR   0
#define LENSYUM_BUG     0
#define LENSYUM_BUILD   1
